apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kaput-not.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kaput-not.labels" . | nindent 4 }}
data:
  # Netmaker API endpoint (non-sensitive)
  NETMAKER_API_URL: {{ .Values.netmaker.apiUrl | quote }}

  # Kubernetes cluster name (optional, for multi-cluster deployments)
  # If empty: single-cluster mode, manages all kaput-not egress rules
  # If set: multi-cluster mode, only manages egress rules with this cluster name
  {{- if .Values.clusterName }}
  K8S_CLUSTER_NAME: {{ .Values.clusterName | quote }}
  {{- end }}

  # Leader election configuration
  # Note: LEADER_ELECTION_ENABLED and LEADER_ELECTION_NAMESPACE are auto-detected
  # when not explicitly set. In-cluster defaults to enabled with pod's namespace.
  # Local development defaults to disabled.
  LEADER_ELECTION_ENABLED: {{ .Values.leaderElection.enabled | quote }}
  LEADER_ELECTION_ID: {{ .Values.leaderElection.id | quote }}
