---
# Default values for kaput-not
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Affinity
affinity: {}

# Annotations to add to all resources
annotations: {}

# Kubernetes cluster name (optional)
# Use this for multi-cluster deployments sharing a Netmaker network
# If empty: single-cluster mode, manages all kaput-not egress rules
# If set: multi-cluster mode, only manages egress rules with this cluster name
clusterName: ""

fullnameOverride: ""

image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/bsure-analytics/kaput-not
  # Overrides the image tag whose default is the chart appVersion
  tag: ""

imagePullSecrets: []

# Labels to add to all resources
labels: {}

# Leader election configuration
leaderElection:
  # Note: enabled defaults to true in-cluster, false for local development
  # Namespace is auto-detected from the pod's service account
  enabled: true
  id: kaput-not

nameOverride: ""

# Netmaker configuration
netmaker:
  # Netmaker API endpoint (required)
  apiUrl: https://api.netmaker.example.com
  # Networks are auto-discovered from Netmaker API based on which networks each host participates in
  # Netmaker credentials (required)
  # You should override these values via --set flags or a separate values file
  # NEVER commit actual credentials to git
  password: REPLACE-WITH-ACTUAL-PASSWORD
  username: kaput-not

# Node selector
nodeSelector: {}

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

priorityClassName: system-cluster-critical

# Number of controller replicas (leader election enabled)
replicaCount: 2

# Resource limits and requests
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Rolling update strategy
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate

# Tolerations
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists

# Topology spread constraints for HA
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
